version: "3.7"
  services:
    front:
      image: <nombre_usuario_Docker_Hub>/front:<version>
    back:
      image: <nombre_usuario_Docker_Hub>/back:<version>
    lb:
      build: ./container-chat-lb-example
      depends_on:
        - front
        - back
      ports:
        - "80:80"